services:
  labelprinter:
    build: .
    container_name: labelprinter
    restart: unless-stopped
    environment:
      - PRINTER_IP=192.168.20.110
      - PRINTER_PORT=9100
    volumes:
      - ./data:/app/data:ro
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true